In [16]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

# Funkcja logiczna OR
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], 'float32')
Y_or = np.array([[0], [1], [1], [1]], 'float32')

model_or = Sequential()
model_or.add(Dense(64, input_dim=2, activation='tanh'))
model_or.add(Dense(32, activation='tanh'))  
model_or.add(Dense(16, activation='tanh'))  
model_or.add(Dense(8, activation='tanh'))  
model_or.add(Dense(1, activation='sigmoid'))

model_or.compile(optimizer='adam', loss='binary_crossentropy')
model_or.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Gate Output:")
print(model_or.predict(X_or))


OR Gate Output:
1/1 [==============================] - 0s 51ms/step
[[0.01444041]
 [0.9880666 ]
 [0.9880595 ]
 [0.98817277]]


In [17]:
# Funkcja logiczna OR
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], 'float32')
Y_or = np.array([[0], [1], [1], [1]], 'float32')


model_or = Sequential()
model_or.add(Dense(16, input_dim=2, activation='tanh'))
model_or.add(Dense(8, activation='tanh')) 
model_or.add(Dense(4, activation='tanh')) 
model_or.add(Dense(1, activation='sigmoid'))


model_or.compile(optimizer='adam', loss='binary_crossentropy')
model_or.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Gate Output:")
print(model_or.predict(X_or))

OR Gate Output:
1/1 [==============================] - 0s 58ms/step
[[0.02666172]
 [0.9832703 ]
 [0.98428196]
 [0.9878885 ]]


In [18]:
# Funkcja logiczna OR
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], 'float32')
Y_or = np.array([[0], [1], [1], [1]], 'float32')


model_or = Sequential()
model_or.add(Dense(16, input_dim=2, activation='tanh'))
model_or.add(Dense(8, activation='tanh')) 
model_or.add(Dense(4, activation='tanh')) 
model_or.add(Dense(1, activation='sigmoid'))


model_or.compile(optimizer='nadam', loss='binary_crossentropy')
model_or.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Gate Output:")
print(model_or.predict(X_or))

OR Gate Output:
1/1 [==============================] - 0s 49ms/step
[[0.02857966]
 [0.9839867 ]
 [0.986036  ]
 [0.98986024]]


In [19]:
# Funkcja logiczna OR
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], 'float32')
Y_or = np.array([[0], [1], [1], [1]], 'float32')


model_or = Sequential()
model_or.add(Dense(16, input_dim=2, activation='tanh'))
model_or.add(Dense(8, activation='tanh')) 
model_or.add(Dense(4, activation='tanh')) 
model_or.add(Dense(1, activation='sigmoid'))


model_or.compile(optimizer='adadelta', loss='binary_crossentropy')
model_or.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Gate Output:")
print(model_or.predict(X_or))

OR Gate Output:
1/1 [==============================] - 0s 45ms/step
[[0.50186753]
 [0.50802845]
 [0.3972503 ]
 [0.40354693]]


In [21]:
# Funkcja logiczna OR
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], 'float32')
Y_or = np.array([[0], [1], [1], [1]], 'float32')


model_or = Sequential()
model_or.add(Dense(16, input_dim=2, activation='tanh'))
model_or.add(Dense(8, activation='tanh')) 
model_or.add(Dense(4, activation='tanh')) 
model_or.add(Dense(1, activation='sigmoid'))


model_or.compile(optimizer='adagrad', loss='binary_crossentropy')
model_or.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Gate Output:")
print(model_or.predict(X_or))

OR Gate Output:
1/1 [==============================] - 0s 45ms/step
[[0.5438038 ]
 [0.63130456]
 [0.6172264 ]
 [0.7007385 ]]
